### ISSUE TITLE
Wrong package name on installation instructions

### ISSUE THREAD

**Issue by loqtor** [wxtiles/wxtilesjs#8]
Hi guys,

Just to let you know that the README has `npm install wx_tiles` when it should be `npm install wx-tiles`.

Cheers!

**Comment by loqtor** [comment]
Sorry, my mistake. Not sure why it did not work for me the first time with `wx_tiles`.

Cheers!

**Comment by loqtor** [comment]
Actually, that did not work for me either. Sorry, I saw it loading and I thought it was ok, but it was not.

Not sure if this package is still available.

Cheers!

<img width="632" alt="screen shot 2018-11-20 at 2 11 05 pm" src="https://user-images.githubusercontent.com/5937874/48744923-30be5c00-ecce-11e8-97d0-acea11c2513f.png">

**Comment by alpha-beta-soup** [comment]
Sorry, this package is not currently maintained. It may be once again in the future.

**Comment by loqtor** [comment]
Awesome. Thanks for getting back to me.

Is there any chance this can be clarified on WXTiles site as well as this repo doc?
Thanks.

Cheers!
